### ISSUE TITLE
Unable to load pictures

### ISSUE THREAD

**Issue by SNWCreations** [asadahimeka/pixiv-viewer-kai#1]
I saw this just now, it is really good!
But I can just view the information, the pictures cannot be loaded.
The problem is happened at the website that referenced in the main repo (The DEMO link)

The website displayed "Network Error", and the pictures cannot be loaded.

**Comment by asadahimeka** [comment]
Maybe you can switch another pximg proxy in the Settings.

**Comment by SNWCreations** [comment]
> Maybe you can switch another pximg proxy in the Settings.

Oh, I saw the settings. It works.
This issue has been solved.
